server.port=8080
server.servlet.context-path=

# Database Configuration
spring.datasource.url=jdbc:h2:mem:moviebookingdb
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# Security
# Disabled CSRF for initial development to allow easier API testing from frontend
spring.security.csrf.enabled=false
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.jackson.visibility.field=ANY
spring.jackson.visibility.getter=NONE
spring.jackson.visibility.is-getter=NONE

spring.thymeleaf.cache=false
